/**
 * Open-Pax — Balance Agent
 * =========================
 * Manages dynamic world state generation via LLM.
 * Generates and updates country data (population, GDP, military, ideology, allies, enemies).
 */

import { MiniMaxProvider } from '../llm';
import { getCountry, type Country } from '../utils/countries';

export interface CountryState {
  code: string;           // USA, RUS, CHN, etc.
  name: string;           // United States, Russia, etc.
  color: string;          // Country color

  // Generated by LLM
  population?: number;     // ~150_000_000
  gdp?: number;          // GDP index (relative)
  military?: number;      // Military index (relative)
  ideology?: string;      // "democracy", "communism", etc.
  allies?: string[];      // ["GBR", "FRA", "DEU"]
  enemies?: string[];     // ["USSR"]

  // Status
  status?: 'superpower' | 'major' | 'regional' | 'minor';
}

export interface WorldState {
  date: string;
  countries: Map<string, CountryState>;
}

export class BalanceAgent {
  private provider: MiniMaxProvider;
  private readonly BATCH_SIZE = 6; // Concurrent LLM calls - balanced for rate limits

  constructor(provider: MiniMaxProvider) {
    this.provider = provider;
  }

  /**
   * Generate initial state for all countries in a template
   * Uses parallel batch processing for speed (~2-3 min instead of 11+ min)
   */
  async generateInitialWorldState(
    template: {
      id: string;
      name: string;
      country_codes: string[];
      base_prompt: string;
      start_date: string;
    }
  ): Promise<WorldState> {
    console.log('[BalanceAgent] Generating initial world state for template:', template.name, '(batch size:', this.BATCH_SIZE, ')');

    const countries = new Map<string, CountryState>();

    // Get valid countries (filter out missing ones upfront)
    const validCountries = template.country_codes
      .map(code => getCountry(code))
      .filter((c): c is Country => c !== null && c !== undefined);

    const total = validCountries.length;
    console.log('[BalanceAgent] Processing', total, 'countries in parallel batches');

    // Process in batches
    for (let i = 0; i < validCountries.length; i += this.BATCH_SIZE) {
      const batch = validCountries.slice(i, i + this.BATCH_SIZE);
      const batchNum = Math.floor(i / this.BATCH_SIZE) + 1;
      const totalBatches = Math.ceil(total / this.BATCH_SIZE);

      console.log(`[BalanceAgent] Batch ${batchNum}/${totalBatches} (${batch.length} countries)...`);

      // Generate state for batch in parallel
      const results = await Promise.all(
        batch.map(country =>
          this.generateCountryState(country, template.start_date, template.base_prompt)
        )
      );

      // Store results
      for (const state of results) {
        countries.set(state.code, state);
      }

      console.log(`[BalanceAgent] Batch ${batchNum}/${totalBatches} complete (${countries.size}/${total} countries done)`);
    }

    // Balance the world (adjust if one country is too dominant)
    await this.balanceWorld(countries);

    console.log('[BalanceAgent] World generation complete:', countries.size, 'countries');
    return {
      date: template.start_date,
      countries,
    };
  }

  /**
   * Generate state for a single country via LLM
   */
  async generateCountryState(
    country: Country,
    date: string,
    worldPrompt: string
  ): Promise<CountryState> {
    const system = `Ты — генератор реалистичных данных для страны в альтернативной истории.

Твоя задача — сгенерировать начальное состояние страны на основе реальных исторических данных.

Правила:
1. Population — реальная численность населения на указанный год
2. GDP — индекс относительно США = 100
3. Military — индекс военной мощи относительно США = 100
4. Ideology — политическая идеология страны
5. Allies — коды стран-союзников (реальные альянсы на тот период)
6. Enemies — коды стран-противников (реальные противоречия)
7. Status — 'superpower', 'major', 'regional', или 'minor'

Формат ответа — ТОЛЬКО JSON:
{
  "population": число,
  "gdp": число,
  "military": число,
  "ideology": "строка",
  "allies": ["код1", "код2"],
  "enemies": ["код1", "код2"],
  "status": "superpower|major|regional|minor"
}`;

    const user = `Страна: ${country.name} (${country.code})
Дата: ${date}
Мир: ${worldPrompt}

Сгенерируй реалистичное начальное состояние этой страны.`;

    try {
      const result = await this.provider.generate(system, user, { temperature: 0.7 });

      // Strip markdown code fences if present
      let jsonContent = result.content.trim();
      if (jsonContent.startsWith('```json')) {
        jsonContent = jsonContent.slice(7);
      } else if (jsonContent.startsWith('```')) {
        jsonContent = jsonContent.slice(3);
      }
      if (jsonContent.endsWith('```')) {
        jsonContent = jsonContent.slice(0, -3);
      }
      jsonContent = jsonContent.trim();

      let parsed = JSON.parse(jsonContent);

      // Ensure arrays and strings
      return {
        code: country.code,
        name: country.name,
        color: country.color,
        population: parsed.population || 10_000_000,
        gdp: parsed.gdp || 50,
        military: parsed.military || 50,
        ideology: parsed.ideology || "neutral",
        allies: parsed.allies || [],
        enemies: parsed.enemies || [],
        status: parsed.status || "regional",
      };
    } catch (e) {
      console.error('[BalanceAgent] Failed to generate state for', country.code, e);
      // Return default state
      return {
        code: country.code,
        name: country.name,
        color: country.color,
        population: 10_000_000,
        gdp: 50,
        military: 50,
        ideology: "neutral",
        allies: [],
        enemies: [],
        status: "regional",
      };
    }
  }

  /**
   * Balance the world — no country should be too dominant
   */
  async balanceWorld(countries: Map<string, CountryState>): Promise<void> {
    // Find superpower(s)
    const superpowers = Array.from(countries.values()).filter(c => c.status === 'superpower');

    if (superpowers.length > 2) {
      // Too many superpowers — demote some
      for (let i = 2; i < superpowers.length; i++) {
        superpowers[i].status = 'major';
        superpowers[i].military = Math.floor((superpowers[i].military || 100) * 0.7);
      }
    }

    if (superpowers.length === 0 && countries.size > 0) {
      // No superpowers — promote the strongest
      const strongest = Array.from(countries.values())
        .sort((a, b) => (b.military || 0) - (a.military || 0))[0];
      if (strongest && strongest.military && strongest.military > 80) {
        strongest.status = 'superpower';
      }
    }

    // Ensure major countries have at least 1 ally
    for (const country of countries.values()) {
      if (country.status === 'major' && (!country.allies || country.allies.length === 0)) {
        // Find nearby country to ally with
        const others = Array.from(countries.keys()).filter(k => k !== country.code);
        if (others.length > 0) {
          country.allies = [others[0]];
        }
      }
    }
  }

  /**
   * Update world state after a time jump
   */
  async updateWorldState(
    currentState: WorldState,
    events: string[],
    jumpDays: number
  ): Promise<WorldState> {
    // For now, apply simple rules based on events
    // In the future, this could use LLM to generate more nuanced updates

    const updatedCountries = new Map(currentState.countries);

    for (const country of updatedCountries.values()) {
      // Simple growth/decline based on events
      for (const event of events) {
        if (event.includes('war') || event.includes('conflict')) {
          country.military = Math.min(200, (country.military || 50) * 1.1);
          country.population = Math.max(1_000_000, (country.population || 10_000_000) * 0.95);
        }
        if (event.includes('economic') || event.includes('crisis')) {
          country.gdp = Math.max(10, (country.gdp || 50) * 0.9);
        }
        if (event.includes('growth') || event.includes('boom')) {
          country.gdp = Math.min(200, (country.gdp || 50) * 1.1);
        }
      }

      // Natural growth (0.1% per month)
      const months = Math.floor(jumpDays / 30);
      const growth = 1 + (0.001 * months);
      country.population = Math.floor((country.population || 10_000_000) * growth);
    }

    return {
      date: this.advanceDate(currentState.date, jumpDays),
      countries: updatedCountries,
    };
  }

  /**
   * Advance date by N days
   */
  private advanceDate(date: string, days: number): string {
    const d = new Date(date);
    d.setDate(d.getDate() + days);
    return d.toISOString().split('T')[0];
  }

  /**
   * Get summary of world state for prompts
   */
  getWorldSummary(state: WorldState): string {
    const lines: string[] = [];

    lines.push(`## Мир на ${state.date}`);
    lines.push('');

    // Group by status
    const superpowers = Array.from(state.countries.values()).filter(c => c.status === 'superpower');
    const majors = Array.from(state.countries.values()).filter(c => c.status === 'major');
    const regionals = Array.from(state.countries.values()).filter(c => c.status === 'regional');

    if (superpowers.length > 0) {
      lines.push('### Сверхдержавы');
      for (const c of superpowers) {
        lines.push(`- **${c.name}** (${c.code}): ${c.population?.toLocaleString()} чел., GDP: ${c.gdp}, Military: ${c.military}`);
        if (c.allies && c.allies.length > 0) {
          lines.push(`  Союзники: ${c.allies.join(', ')}`);
        }
        if (c.enemies && c.enemies.length > 0) {
          lines.push(`  Противники: ${c.enemies.join(', ')}`);
        }
      }
      lines.push('');
    }

    if (majors.length > 0) {
      lines.push('### Крупные державы');
      for (const c of majors) {
        lines.push(`- ${c.name} (${c.code}): ${c.population?.toLocaleString()} чел.`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }
}
